# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - MWO4

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
   
    steps:
      - uses: actions/checkout@v4
      - uses: ikalnytskyi/action-setup-postgres@v4
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'
          include-prerelease: true
          
      - name: Restore Dependencies
        run: dotnet workload restore
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
        
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: add migration
        run: |
          cd P05Shop.API
          dotnet tool restore
          dotnet ef migrations add mgrt1
          dotnet ef database update
          cd ..
      
      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
      - name: Run Application
        run: |
          cd P05Shop.API
          cmd /c "start dotnet run --urls=http://localhost:5093"
          cd ../MVCBlazorClient
          cmd /c "start dotnet run --urls=http://localhost:5123"
          cd ..
          dotnet test
          exit 1
          
      - name: Create Ticket
        if: failure()
        run: |
          echo '[{
            "op": "add",
            "path": "/fields/System.Title",
            "from": null,
            "value": "UI test failed"
          }]' > workitem.json
          echo "Azure DevOps Token: $AZURE_DEVOPS_TOKEN"
          echo "API URL: https://dev.azure.com/01171749/MWO4/_apis/wit/workitems/\$Issue?api-version=7.1-preview.3"
          curl -g -X POST -H "Content-Type: application/json-patch+json" -H "Authorization: Basic ${{ secrets.PAT }}" --data "@ticket.json" "https://dev.azure.com/01171749/MWO4/_apis/wit/workitems/%24Issue?api-version=7.1-preview.3" -o response.json
          cat response.json
        env:
          AZURE_DEVOPS_TOKEN: ${{ secrets.PAT }}
          
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MWO4'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_77516E9E06F44233BEF233DCDF234D47 }}
          package: .
